language: elixir
elixir:
  - 1.10.4
otp_release:
  - 23.0.3
env:
  - MIX_ENV=test
script:
  - mix do deps.get, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - _build
  - deps
